import { GrowCardTemplate } from '../types';

/** Full HTML from backend — 1080×1080 birthday card. Frontend replaces {NAME}, {FIRST_NAME}, {GREETING}, {MESSAGE}. */
export const BIRTHDAY_CARD_HTML = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Happy Birthday, {FIRST_NAME}!</title></head><body style="margin: 0; padding: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"><div style="width: 1080px; height: 1080px; overflow: hidden; position: relative; background: linear-gradient(135deg, #FFC0CB 0%, #FFD700 50%, #87CEEB 100%); box-shadow: 0 4px 20px rgba(0,0,0,0.1); display: flex; justify-content: center; align-items: center;"><div style="position: absolute; top: 8%; left: 15%; width: 35px; height: 35px; background-color: #FF69B4; border-radius: 50%; transform: rotate(15deg) scale(0.9);"></div><div style="position: absolute; top: 18%; right: 18%; width: 25px; height: 25px; background-color: #FFA07A; border-radius: 50%; transform: rotate(40deg) scale(1.1);"></div><div style="position: absolute; bottom: 10%; left: 28%; width: 45px; height: 45px; background-color: #ADFF2F; border-radius: 50%; transform: rotate(-25deg) scale(1.2);"></div><div style="position: absolute; bottom: 15%; right: 8%; width: 30px; height: 30px; background-color: #9370DB; border-radius: 50%; transform: rotate(10deg) scale(0.8);"></div><div style="position: absolute; top: 30%; left: 5%; width: 20px; height: 20px; background-color: #FFD700; border-radius: 50%;"></div><div style="position: absolute; top: 45%; right: 30%; width: 22px; height: 22px; background-color: #00CED1; border-radius: 50%; transform: rotate(55deg);"></div><div style="position: absolute; top: 22%; left: 40%; width: 18px; height: 18px; background-color: #FFD700; transform: rotate(30deg);"></div><div style="position: absolute; bottom: 20%; right: 40%; width: 20px; height: 20px; background-color: #FF69B4; transform: rotate(-10deg);"></div><div style="position: absolute; top: 60%; left: 10%; width: 15px; height: 15px; background-color: #ADFF2F; transform: rotate(70deg);"></div><div style="position: relative; width: 75%; max-width: 850px; padding: 50px; background-color: rgba(255, 255, 255, 0.95); border-radius: 30px; text-align: center; box-shadow: 0 10px 40px rgba(0,0,0,0.25);"><h1 style="color: #0066CC; font-size: 68px; margin-bottom: 20px; font-weight: 800; letter-spacing: -1.5px; text-shadow: 2px 2px 5px rgba(0,0,0,0.1);">Happy Birthday, {FIRST_NAME}! 🎉</h1><p style="color: #444; font-size: 30px; line-height: 1.5; max-width: 680px; margin: 0 auto 35px auto; font-weight: 500;">{MESSAGE}</p></div><div style="position: absolute; bottom: 40px; left: 50%; transform: translateX(-50%); text-align: center; display: flex; align-items: center;"><span style="color: #0066CC; font-size: 40px; font-weight: 800; text-transform: uppercase; letter-spacing: 2px;">PolicyBazaar</span><span style="color: #666; font-size: 26px; font-weight: 500; margin-left: 12px; letter-spacing: 0.5px;">Partners</span></div></div></body></html>`;

export const MOCK_GROW_CARD_TEMPLATES: GrowCardTemplate[] = [
  {
    id: 'birthday',
    title: 'Happy Birthday',
    shareMessageTemplate:
      '{GREETING} {NAME}! Wishing you a very Happy Birthday filled with health, happiness, and success! 🎉 — PolicyBazaar Partners',
    html: BIRTHDAY_CARD_HTML,
  },
];
