import pool from '../config/database';

/**
 * Seed demo customers — tuned so the formula naturally produces target scores.
 *
 * Anjali Mehta (C5501): PIS=62, OS=89
 * Rohit Verma (C5502):  PIS=45, OS=46
 * Priya Nair (C5503):   PIS=84, OS=41
 *
 * Plus 7 additional customers for a richer demo database.
 */

const PARTNER_ID = 'P001';
const PARTNER_ID_2 = 'P002';

const customers = [
  // ═══════════════════════════════════════════════
  // THREE DEMO CUSTOMERS (Partner P001)
  // ═══════════════════════════════════════════════
  {
    // Anjali Mehta — Motor ✓, Life ✓, Health ✗, Term ✗
    // Target PIS: 62, Target OS: 89
    external_id: 'C5501',
    first_name: 'Anjali',
    last_name: 'Mehta',
    email: 'anjali.mehta@example.com',
    phone: '9876543210',
    date_of_birth: '1990-03-15',
    gender: 'FEMALE',
    marital_status: 'MARRIED',
    life_stage: 'GROWING_FAMILY',
    dependents: 2,
    annual_income: 1200000,
    occupation: 'Software Engineer',
    smoker: false,
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    existing_liabilities: 5000000,
    total_assets: 8000000,
    health_cover: false,
    term_cover: false,
    life_cover: true,
    motor_cover: true,
    external_policies: 1,
    coverage_source: JSON.stringify({ motor: 'pb_held', life: 'pb_held' }),
    children: 0,       // No children (removes FRP bonus & LSR bonus)
    elderly_parent_dependent: true,
    single_earner: true,
    home_loan: true,
    renewal_due_days: 9,
    last_interaction_days: 15,
    known_pb_policies: 2,
    profile_complete: true,
    partner_id: PARTNER_ID,
  },
  {
    // Rohit Verma — Motor ✓, Life ✗, Health ✗, Term ✗
    // Target PIS: 45, Target OS: 46
    external_id: 'C5502',
    first_name: 'Rohit',
    last_name: 'Verma',
    email: 'rohit.verma@example.com',
    phone: '9876543211',
    date_of_birth: '1985-08-22',
    gender: 'MALE',
    marital_status: 'MARRIED',
    life_stage: 'ESTABLISHED_FAMILY',
    dependents: 1,
    annual_income: 900000,
    occupation: 'Accountant',
    smoker: false,
    city: 'Delhi',
    state: 'Delhi',
    pincode: '110001',
    existing_liabilities: 3000000,
    total_assets: 5000000,
    health_cover: false,
    term_cover: false,
    life_cover: false,
    motor_cover: true,
    external_policies: 1,
    coverage_source: JSON.stringify({ motor: 'pb_held' }),
    children: 1,
    elderly_parent_dependent: false,
    single_earner: true,
    home_loan: true,
    renewal_due_days: 95,
    last_interaction_days: 45,
    known_pb_policies: 2,
    profile_complete: true,
    partner_id: PARTNER_ID,
  },
  {
    // Priya Nair — Motor ✓, Life ✓, Health ✓, Term ✗
    // Target PIS: 84, Target OS: 41
    external_id: 'C5503',
    first_name: 'Priya',
    last_name: 'Nair',
    email: 'priya.nair@example.com',
    phone: '9876543212',
    date_of_birth: '1988-11-10',
    gender: 'FEMALE',
    marital_status: 'MARRIED',
    life_stage: 'GROWING_FAMILY',
    dependents: 2,
    annual_income: 1500000,
    occupation: 'Doctor',
    smoker: false,
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560001',
    existing_liabilities: 2000000,
    total_assets: 12000000,
    health_cover: true,
    term_cover: false,
    life_cover: true,
    motor_cover: true,
    external_policies: 1,
    coverage_source: JSON.stringify({ motor: 'pb_held', life: 'pb_held', health: 'pb_held' }),
    children: 2,
    elderly_parent_dependent: true,
    single_earner: true,
    home_loan: true,
    renewal_due_days: 45,
    last_interaction_days: 60,
    known_pb_policies: 3,
    profile_complete: true,
    partner_id: PARTNER_ID,
  },

  // ═══════════════════════════════════════════════
  // ADDITIONAL CUSTOMERS (for richer database)
  // ═══════════════════════════════════════════════
  {
    external_id: 'C5504',
    first_name: 'Vikram',
    last_name: 'Singh',
    email: 'vikram.singh@example.com',
    phone: '9876543213',
    date_of_birth: '1982-05-20',
    gender: 'MALE',
    marital_status: 'MARRIED',
    life_stage: 'ESTABLISHED_FAMILY',
    dependents: 3,
    annual_income: 2000000,
    occupation: 'Business Owner',
    smoker: true,
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411001',
    existing_liabilities: 8000000,
    total_assets: 15000000,
    health_cover: true,
    term_cover: true,
    life_cover: true,
    motor_cover: true,
    external_policies: 2,
    coverage_source: JSON.stringify({ motor: 'pb_held', life: 'pb_held', health: 'sold_by_agent', term: 'added_by_agent' }),
    children: 3,
    elderly_parent_dependent: true,
    single_earner: true,
    home_loan: true,
    renewal_due_days: 180,
    last_interaction_days: 5,
    known_pb_policies: 2,
    profile_complete: true,
    partner_id: PARTNER_ID,
  },
  {
    external_id: 'C5505',
    first_name: 'Meera',
    last_name: 'Patel',
    email: 'meera.patel@example.com',
    phone: '9876543214',
    date_of_birth: '1995-01-12',
    gender: 'FEMALE',
    marital_status: 'SINGLE',
    life_stage: 'YOUNG_SINGLE',
    dependents: 0,
    annual_income: 600000,
    occupation: 'Marketing Executive',
    smoker: false,
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380001',
    existing_liabilities: 0,
    total_assets: 800000,
    health_cover: false,
    term_cover: false,
    life_cover: false,
    motor_cover: true,
    external_policies: 0,
    coverage_source: JSON.stringify({ motor: 'pb_held' }),
    children: 0,
    elderly_parent_dependent: false,
    single_earner: false,
    home_loan: false,
    renewal_due_days: 25,
    last_interaction_days: 3,
    known_pb_policies: 1,
    profile_complete: false,
    partner_id: PARTNER_ID,
  },
  {
    external_id: 'C5506',
    first_name: 'Arjun',
    last_name: 'Reddy',
    email: 'arjun.reddy@example.com',
    phone: '9876543215',
    date_of_birth: '1978-09-30',
    gender: 'MALE',
    marital_status: 'MARRIED',
    life_stage: 'PRE_RETIREMENT',
    dependents: 2,
    annual_income: 3500000,
    occupation: 'Senior VP - Banking',
    smoker: false,
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500001',
    existing_liabilities: 2000000,
    total_assets: 25000000,
    health_cover: true,
    term_cover: true,
    life_cover: true,
    motor_cover: true,
    external_policies: 3,
    coverage_source: JSON.stringify({ motor: 'pb_held', life: 'pb_held', health: 'pb_held', term: 'added_by_agent' }),
    children: 2,
    elderly_parent_dependent: true,
    single_earner: false,
    home_loan: false,
    renewal_due_days: 200,
    last_interaction_days: 60,
    known_pb_policies: 3,
    profile_complete: true,
    partner_id: PARTNER_ID,
  },
  {
    external_id: 'C5507',
    first_name: 'Sneha',
    last_name: 'Gupta',
    email: 'sneha.gupta@example.com',
    phone: '9876543216',
    date_of_birth: '1992-07-08',
    gender: 'FEMALE',
    marital_status: 'MARRIED',
    life_stage: 'NEW_PARENT',
    dependents: 1,
    annual_income: 1800000,
    occupation: 'Product Manager',
    smoker: false,
    city: 'Gurgaon',
    state: 'Haryana',
    pincode: '122001',
    existing_liabilities: 6000000,
    total_assets: 10000000,
    health_cover: true,
    term_cover: false,
    life_cover: true,
    motor_cover: true,
    external_policies: 0,
    coverage_source: JSON.stringify({ motor: 'pb_held', life: 'pb_held', health: 'sold_by_agent' }),
    children: 1,
    elderly_parent_dependent: false,
    single_earner: true,
    home_loan: true,
    renewal_due_days: 12,
    last_interaction_days: 8,
    known_pb_policies: 2,
    profile_complete: true,
    partner_id: PARTNER_ID_2,
  },
  {
    external_id: 'C5508',
    first_name: 'Rajesh',
    last_name: 'Kumar',
    email: 'rajesh.kumar@example.com',
    phone: '9876543217',
    date_of_birth: '1975-12-25',
    gender: 'MALE',
    marital_status: 'MARRIED',
    life_stage: 'ESTABLISHED_FAMILY',
    dependents: 4,
    annual_income: 800000,
    occupation: 'Teacher',
    smoker: false,
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    pincode: '226001',
    existing_liabilities: 1500000,
    total_assets: 3000000,
    health_cover: false,
    term_cover: false,
    life_cover: true,
    motor_cover: true,
    external_policies: 0,
    coverage_source: JSON.stringify({ motor: 'pb_held', life: 'added_by_agent' }),
    children: 4,
    elderly_parent_dependent: true,
    single_earner: true,
    home_loan: true,
    renewal_due_days: 20,
    last_interaction_days: 40,
    known_pb_policies: 1,
    profile_complete: false,
    partner_id: PARTNER_ID_2,
  },
  {
    external_id: 'C5509',
    first_name: 'Kavitha',
    last_name: 'Menon',
    email: 'kavitha.menon@example.com',
    phone: '9876543218',
    date_of_birth: '1993-04-18',
    gender: 'FEMALE',
    marital_status: 'SINGLE',
    life_stage: 'YOUNG_SINGLE',
    dependents: 0,
    annual_income: 1000000,
    occupation: 'Data Scientist',
    smoker: false,
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600001',
    existing_liabilities: 500000,
    total_assets: 2000000,
    health_cover: true,
    term_cover: false,
    life_cover: false,
    motor_cover: true,
    external_policies: 1,
    coverage_source: JSON.stringify({ motor: 'pb_held', health: 'pb_held' }),
    children: 0,
    elderly_parent_dependent: true,
    single_earner: false,
    home_loan: false,
    renewal_due_days: 150,
    last_interaction_days: 20,
    known_pb_policies: 2,
    profile_complete: true,
    partner_id: PARTNER_ID_2,
  },
  {
    external_id: 'C5510',
    first_name: 'Aditya',
    last_name: 'Sharma',
    email: 'aditya.sharma@example.com',
    phone: '9876543219',
    date_of_birth: '1987-06-02',
    gender: 'MALE',
    marital_status: 'DIVORCED',
    life_stage: 'ESTABLISHED_FAMILY',
    dependents: 1,
    annual_income: 2500000,
    occupation: 'Architect',
    smoker: false,
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302001',
    existing_liabilities: 4000000,
    total_assets: 9000000,
    health_cover: true,
    term_cover: true,
    life_cover: false,
    motor_cover: true,
    external_policies: 1,
    coverage_source: JSON.stringify({ motor: 'pb_held', health: 'pb_held', term: 'sold_by_agent' }),
    children: 1,
    elderly_parent_dependent: false,
    single_earner: true,
    home_loan: true,
    renewal_due_days: 70,
    last_interaction_days: 35,
    known_pb_policies: 2,
    profile_complete: true,
    partner_id: PARTNER_ID_2,
  },
];

async function seed() {
  console.log('🌱 Seeding customers...\n');

  try {
    // Clear existing data
    const externalIds = customers.map(c => c.external_id);
    await pool.query(`DELETE FROM customers WHERE external_id = ANY($1)`, [externalIds]);

    for (const c of customers) {
      const query = `
        INSERT INTO customers (
          external_id, first_name, last_name, email, phone, date_of_birth,
          gender, marital_status, life_stage, dependents, annual_income,
          occupation, smoker, city, state, pincode,
          existing_liabilities, total_assets,
          health_cover, term_cover, life_cover, motor_cover,
          external_policies, coverage_source,
          children, elderly_parent_dependent, single_earner, home_loan,
          renewal_due_days, last_interaction_days, known_pb_policies, profile_complete,
          partner_id
        ) VALUES (
          $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,
          $19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33
        ) RETURNING id, external_id, first_name, last_name
      `;

      const values = [
        c.external_id, c.first_name, c.last_name, c.email, c.phone, c.date_of_birth,
        c.gender, c.marital_status, c.life_stage, c.dependents, c.annual_income,
        c.occupation, c.smoker, c.city, c.state, c.pincode,
        c.existing_liabilities, c.total_assets,
        c.health_cover, c.term_cover, c.life_cover, c.motor_cover,
        c.external_policies, c.coverage_source,
        c.children, c.elderly_parent_dependent, c.single_earner, c.home_loan,
        c.renewal_due_days, c.last_interaction_days, c.known_pb_policies, c.profile_complete,
        c.partner_id,
      ];

      const result = await pool.query(query, values);
      const row = result.rows[0];
      console.log(`   ✅ ${row.first_name} ${row.last_name} (${row.external_id}) → ID: ${row.id}`);
    }

    console.log(`\n🎉 Seed complete! ${customers.length} customers created.`);
    console.log('   Partner P001: Anjali, Rohit, Priya, Vikram, Meera, Arjun');
    console.log('   Partner P002: Sneha, Rajesh, Kavitha, Aditya');
  } catch (error) {
    console.error('❌ Seed failed:', error);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

seed();
